### PR TITLE
fix bug #12

### LINKED ISSUE #12: Bug Report: Can't start project with the error - "org.mybatis.spring.support.SqlSessionDaoSupport.getSqlSession()" is null
Error creating bean with name 'sysUserMapper' defined in file [~/github/base-backend/backend-system/target/classes/tech/ynfy/module/user/mapper/SysUserMapper.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "org.apache.ibatis.session.SqlSession.getConfiguration()" because the return value of "org.mybatis.spring.support.SqlSessionDaoSupport.getSqlSession()" is null

### PR DESCRIPTION
**Pull request by hsiong**
+ remove druid
+ close #12

### CODE REVIEW

**Comment by shanerobinsonFAGADBDASB** [comment]
When will Brother Xiong engage in python projects?

**Review by shanerobinsonFAGADBDASB — COMMENTED** [review]
When will Brother Xiong engage in python projects?

**Review by chuzilaolin — COMMENTED** [review]
When will Brother Xiong engage in python projects?

**Review by shanerobinsonFAGADBDASB — COMMENTED** [review]
great

**Review by chuzilaolin — COMMENTED** [review]
"Why is the version name for the package <artifactId>springdoc-openapi-ui</artifactId> swagger-springdoc-core.version instead of springdoc-openapi-ui.version?"

**Review by shanerobinsonFAGADBDASB — COMMENTED** [review]
Why is the version name for the package <artifactId>springdoc-openapi-ui</artifactId> swagger-springdoc-core.version instead of springdoc-openapi-ui.version?

**Comment by hsiong** [comment]
> Why is the version name for the package springdoc-openapi-ui swagger-springdoc-core.version instead of springdoc-openapi-ui.version?

You are right. I've changed the property name of springdoc-openapi-ui's version. Please PTAL again, THX.  😊

**Review by chuzilaolin — APPROVED** [review]

**Pull request merged**
